# Generated by Django 4.2.7 on 2025-11-01 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_initial'),
    ]

    operations = [
        # Add payment_rail field to Transaction
        migrations.AddField(
            model_name='transaction',
            name='payment_rail',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money'), ('BANK', 'Bank Transfer')], default='MTN', max_length=20),
        ),
        
        # Update Transaction currency default to ZMW
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='ZMW', max_length=3),
        ),
        
        # Rename Wallet balance field to escrow_balance
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='escrow_balance',
        ),
        
        # Add rewards_balance to Wallet
        migrations.AddField(
            model_name='wallet',
            name='rewards_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        
        # Update Wallet currency default to ZMW
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='ZMW', max_length=3),
        ),
        
        # Update Wallet daily_limit default
        migrations.AlterField(
            model_name='wallet',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12),
        ),
        
        # Create PendingClaim model
        migrations.CreateModel(
            name='PendingClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('message', models.TextField(blank=True, null=True)),
                ('claim_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('invite_sent', models.BooleanField(default=False)),
                ('invite_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_claim', to='transactions.transaction')),
            ],
        ),
        
        # Create PaymentRequest model
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('payer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ZMW', max_length=3)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        
        # Create Referral model
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referred_phone', models.CharField(max_length=20)),
                ('referral_code', models.CharField(max_length=16, unique=True)),
                ('referrer_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('referred_reward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('rewards_paid', models.BooleanField(default=False)),
                ('signup_completed', models.BooleanField(default=False)),
                ('first_transaction_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
