# Generated by Django 4.2.7 on 2025-11-01 09:26

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        # Update User default_currency to ZMW
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.CharField(default='ZMW', max_length=3),
        ),
        
        # Update User daily_limit for Tier 2 KYC
        migrations.AlterField(
            model_name='user',
            name='daily_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('25000'), max_digits=10),
        ),
        
        # Update UserProfile country default to Zambia
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Zambia', max_length=100),
        ),
        
        # Add new KYC fields to UserProfile
        migrations.AddField(
            model_name='userprofile',
            name='proof_of_address',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/poa/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selfie_document',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfie/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=1),
        ),
    ]
